#!/bin/ash
# DNScrypt-Proxy Entry File

echo $(date) - Starting DNScrypt-Proxy

if [ ! -e /data/dnscrypt-proxy.toml ]; then
    cp /etc/dnscrypt-proxy/dnscrypt-proxy.toml /data/dnscrypt-proxy.toml
fi

/usr/bin/dnscrypt-proxy -config /data/dnscrypt-proxy.toml -check
if [ $? -eq 0 ]; then
    echo Configuration check successful.
else
    echo Configuration check failed. Startup aborted.
    exit 1
fi

/usr/bin/dnscrypt-proxy -config /data/dnscrypt-proxy.toml

exit 0
