#!/bin/ash
# DNScrypt-Proxy Entry File

if [ ! -e /data/dnscrypt-proxy.toml ]; then
    cp /etc/dnscrypt-proxy/dnscrypt-proxy.toml /data/dnscrypt-proxy.toml
fi

/usr/bin/dnscrypt-proxy -config /data/dnscrypt-proxy.toml -check && echo Configuration check successful. || echo Configuration check failed. Startup aborted. && exit 1

/usr/bin/dnscrypt-proxy -config /data/dnscrypt-proxy.toml

exit 0
